# Generated by Django 5.2 on 2025-04-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_id', models.CharField(max_length=100)),
                ('cus_name', models.CharField(max_length=100)),
                ('cus_mobile', models.CharField(max_length=100)),
                ('cus_email', models.CharField(max_length=100)),
                ('cus_password', models.CharField(max_length=100)),
                ('image_name', models.CharField(max_length=100)),
                ('image_type', models.CharField(max_length=100)),
                ('image_path', models.CharField(max_length=100)),
                ('haroscope_file_path', models.CharField(max_length=100)),
                ('profile_for', models.CharField(max_length=100)),
                ('name_for', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('mothertongue', models.CharField(max_length=100)),
                ('caste', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=100)),
                ('diet', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('work', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=200)),
                ('cus_credits', models.IntegerField()),
                ('trust_mark', models.IntegerField()),
                ('switch_1', models.IntegerField()),
                ('switch_2', models.IntegerField()),
                ('t_c', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField()),
                ('trn_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
    ]
