# Generated by Django 5.2 on 2025-04-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0002_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=100)),
                ('amt', models.CharField(max_length=100)),
                ('credit', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'plan',
                'managed': False,
            },
        ),
    ]
