# Generated by Django 5.2 on 2025-05-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0003_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryTran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('cus_id', models.IntegerField()),
                ('tran_no', models.CharField(max_length=100)),
                ('plan', models.CharField(max_length=100)),
                ('amt', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('emp_id', models.IntegerField()),
            ],
            options={
                'db_table': 'history_tran',
                'managed': False,
            },
        ),
    ]
