# Generated by Django 5.2 on 2025-05-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0004_historytran'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('cus_id', models.CharField(max_length=100)),
                ('cus_unlock_ids', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'history_unlock',
                'managed': False,
            },
        ),
    ]
