# Generated by Django 5.2 on 2025-05-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0005_historyunlock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=10000)),
                ('blog_img_name', models.CharField(max_length=100)),
                ('blog_img_path', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'blog',
                'managed': False,
            },
        ),
    ]
